// GENERATED by tools/capture_state.cpp against the v0.1 parameter layout.
// Do not edit by hand and do not regenerate after the layout changes -- the
// whole point is that these are the values a real pre-upgrade document holds.
#pragma once

namespace v01Fixture
{
    struct Param { const char* id; float value; };

    inline constexpr Param params[] = {
        { "mix", 62.500000f },
        { "predelay", 137.000000f },
        { "size", 143.000000f },
        { "decay", 7.499999f },
        { "damping", 3199.999756f },
        { "lowcut", 209.999985f },
        { "bandwidth", 11000.000000f },
        { "diffusion", 33.000000f },
        { "moddepth", 81.000000f },
        { "modrate", 1.750000f },
        { "width", 165.000000f },
        { "freeze", 1.000000f },
        { "output", -6.500000f },
    };

    inline constexpr int program     = 5;
    inline constexpr int editorWidth = 880;
    inline constexpr int editorHeight= 610;
}
