/*
    Captures a REAL v0.1 plugin state blob as a test fixture.

    This must run BEFORE the parameter layout changes. Once new parameters exist, a genuine
    pre-upgrade document can no longer be produced, and the state-compatibility test would be
    reduced to asserting against a hand-written approximation of one.

    Writes:
      tests/fixtures/v01-state.bin  - the exact bytes getStateInformation() produced
      tests/fixtures/v01-state.xml  - same content, readable, for diagnosis only
      tests/fixtures/v01-state.h    - the expected values, as a header the test compiles against

    Usage:  WarehouseCaptureState [output-directory]
*/

#include <juce_audio_processors/juce_audio_processors.h>

#include "PluginProcessor.h"

namespace
{
    struct Expected { const char* id; float value; };

    // Deliberately awkward values: every one is off its default, none is a round number that
    // could coincide with a default or a midpoint, and each is inside its parameter's range.
    const Expected expected[] = {
        { "mix",       62.5f },
        { "predelay", 137.0f },
        { "size",     143.0f },
        { "decay",      7.5f },
        { "damping",  3200.0f },
        { "lowcut",    210.0f },
        { "bandwidth", 11000.0f },
        { "diffusion",  33.0f },
        { "moddepth",   81.0f },
        { "modrate",     1.75f },
        { "width",     165.0f },
        { "freeze",      1.0f },
        { "output",     -6.5f },
    };

    constexpr int expectedProgram = 5;
    constexpr int expectedEditorW = 880;
    constexpr int expectedEditorH = 610;
}

int main (int argc, char** argv)
{
    juce::ScopedJuceInitialiser_GUI juceInit;

    const auto cwd    = juce::File::getCurrentWorkingDirectory();
    const auto outDir = argc > 1 ? cwd.getChildFile (juce::String (argv[1]))
                                 : cwd.getChildFile ("tests/fixtures");
    outDir.createDirectory();

    ReverbAudioProcessor processor;
    processor.prepareToPlay (48000.0, 512);

    // Program first: applyPreset writes parameter values, so setting it after would clobber them.
    processor.setCurrentProgram (expectedProgram);
    processor.saveEditorSize (expectedEditorW, expectedEditorH);

    int failures = 0;

    for (const auto& e : expected)
    {
        auto* raw = processor.apvts.getParameter (e.id);

        if (raw == nullptr)
        {
            std::printf ("[FAIL] no such parameter: %s\n", e.id);
            ++failures;
            continue;
        }

        auto* ranged = dynamic_cast<juce::RangedAudioParameter*> (raw);

        if (ranged == nullptr)
        {
            std::printf ("[FAIL] %s is not a RangedAudioParameter\n", e.id);
            ++failures;
            continue;
        }

        ranged->setValueNotifyingHost (ranged->convertTo0to1 (e.value));
    }

    // Read back what actually landed, so the fixture header records reality rather than intent
    // (a value outside a range, or snapped by an interval, would otherwise be recorded wrongly).
    juce::MemoryBlock state;
    processor.getStateInformation (state);

    if (state.getSize() == 0)
    {
        std::printf ("[FAIL] getStateInformation produced 0 bytes\n");
        return 1;
    }

    const auto binFile = outDir.getChildFile ("v01-state.bin");
    binFile.deleteFile();

    if (! binFile.replaceWithData (state.getData(), state.getSize()))
    {
        std::printf ("[FAIL] could not write %s\n", binFile.getFullPathName().toRawUTF8());
        return 1;
    }

    // Readable copy, for diagnosis only. Never parsed by a test.
    //
    // getStateInformation uses copyXmlToBinary, which writes XML TEXT behind a small binary
    // header -- it is not a binary ValueTree, so ValueTree::readFromData produces garbage on it
    // (it yielded "<VC2!c/>" on the first attempt). AudioProcessor::getXmlFromBinary is
    // protected, so find the start of the XML text and dump from there.
    {
        const auto* bytes = static_cast<const char*> (state.getData());
        const auto  size  = static_cast<int> (state.getSize());

        int start = 0;
        while (start < size && bytes[start] != '<')
            ++start;

        if (start < size)
            outDir.getChildFile ("v01-state.xml")
                  .replaceWithText (juce::String::fromUTF8 (bytes + start, size - start));
        else
            outDir.getChildFile ("v01-state.xml")
                  .replaceWithText ("(no XML text found in the state blob)");
    }

    // The expectations header: what a post-upgrade build must restore from the blob above.
    juce::String header;
    header << "// GENERATED by tools/capture_state.cpp against the v0.1 parameter layout.\n"
           << "// Do not edit by hand and do not regenerate after the layout changes -- the\n"
           << "// whole point is that these are the values a real pre-upgrade document holds.\n"
           << "#pragma once\n\n"
           << "namespace v01Fixture\n{\n"
           << "    struct Param { const char* id; float value; };\n\n"
           << "    inline constexpr Param params[] = {\n";

    for (const auto& e : expected)
    {
        auto* ranged = dynamic_cast<juce::RangedAudioParameter*> (processor.apvts.getParameter (e.id));
        const float actual = ranged != nullptr
                                 ? ranged->convertFrom0to1 (ranged->getValue())
                                 : e.value;

        header << "        { \"" << e.id << "\", " << juce::String (actual, 6) << "f },\n";

        std::printf ("  %-10s requested %10.4f   stored %10.4f%s\n",
                     e.id, e.value, actual,
                     std::abs (actual - e.value) > 1.0e-3f ? "   <- SNAPPED" : "");
    }

    header << "    };\n\n"
           << "    inline constexpr int program     = " << expectedProgram << ";\n"
           << "    inline constexpr int editorWidth = " << expectedEditorW << ";\n"
           << "    inline constexpr int editorHeight= " << expectedEditorH << ";\n"
           << "}\n";

    outDir.getChildFile ("v01-state.h").replaceWithText (header);

    std::printf ("\n%s: %d bytes -> %s\n",
                 failures == 0 ? "CAPTURED" : "CAPTURED WITH FAILURES",
                 (int) state.getSize(), binFile.getFullPathName().toRawUTF8());

    return failures == 0 ? 0 : 1;
}
